name: Build

on:
  schedule:
    - cron:  '*/5 * * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        targetplatform: [x64]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install NuGet
      uses: NuGet/setup-nuget@v1
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Install Solution Dependencies
      run: dotnet restore
    - name: Build unp4k Debug
      run: dotnet build --configuration Debug --no-restore
    - name: Build unp4k Release
      run: dotnet build --configuration Release --no-restore
    - name: Test unp4k
      run: dotnet test --no-restore --verbosity normal
