# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: unp4k Build
# Change branches to develop when merged!
on:
  push:
    branches: [ "feature/rewrite" ]
  pull_request:
    branches: [ "feature/rewrite" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Setup .NET WASM
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json
    - name: Restore Git Submodules
      run: git submodule update --init --recursive
    - name: Restore .NET Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
